
package AcertarNumero;


import static AcertarNumero.Musica.playErrou;
import static AcertarNumero.Musica.playErrou2;
import static AcertarNumero.Musica.playSound;

/**
 *
 * @author olivi
 */
public class FrmAcertar extends javax.swing.JFrame {
     int numant = 0;
     int placar1 = 0;
     int placar2 = 0;
    
    
    public FrmAcertar() {  //CONTRUTOR
        initComponents();
        lblFrase.setText("<html>Consegue acertar? pense em um número de 1 a 5</html>");
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        lblFrase = new javax.swing.JLabel();
        txtNum = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        btnSorteio = new javax.swing.JButton();
        lblNumCorr = new javax.swing.JLabel();
        lblNumAnt = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSegundo = new javax.swing.JTextField();
        txtPrimeiro = new javax.swing.JTextField();
        lblPlacar2 = new javax.swing.JLabel();
        lblPlacar1 = new javax.swing.JLabel();
        btnJogador2 = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Numero Anterior");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 160, 30));

        lblFrase.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblFrase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFrase.setText("Frase");
        lblFrase.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblFrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 180, 80));

        txtNum.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtNum.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(txtNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 80, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/balao.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 290, 200));

        btnSorteio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSorteio.setText("Jogador 1");
        btnSorteio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSorteioActionPerformed(evt);
            }
        });
        getContentPane().add(btnSorteio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 140, 40));

        lblNumCorr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNumCorr.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lblNumCorr, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 240, 20));

        lblNumAnt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(lblNumAnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 60, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Escolha um Numero de 1 a 5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 270, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AcertarNumero/mariana400.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 10, 390, 420));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Placar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 140, -1));

        txtSegundo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSegundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSegundoActionPerformed(evt);
            }
        });
        getContentPane().add(txtSegundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 120, -1));

        txtPrimeiro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimeiroActionPerformed(evt);
            }
        });
        getContentPane().add(txtPrimeiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 120, -1));

        lblPlacar2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPlacar2.setText("0");
        getContentPane().add(lblPlacar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 40, -1));

        lblPlacar1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPlacar1.setText("0");
        getContentPane().add(lblPlacar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 40, -1));

        btnJogador2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnJogador2.setText("Jogador 2");
        btnJogador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogador2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnJogador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 120, 40));

        btnIniciar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(204, 0, 0));
        btnIniciar.setText("Iniciar Jogo");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, -1, -1));

        setSize(new java.awt.Dimension(830, 613));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSorteioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSorteioActionPerformed
       // Sorteia um número de 1 a 5
       
        lblNumAnt.setText(Integer.toString(numant));    
        double numsorte = (Math.random()* (6 - 1) + 1);
        int resultado = (int)numsorte;
        int valor = Integer.parseInt(txtNum.getValue().toString()); 
        lblNumCorr.setText("Sorteado è o Número " + resultado);
          if (resultado == valor){
              lblFrase.setText("Acertou");
               playSound();
               placar1 = placar1 + 1;
               lblPlacar1.setText(Integer.toString(placar1));
               
          }else{
              lblFrase.setText("Errou");
              playErrou2();
           }   
            numant=resultado;
        
    }//GEN-LAST:event_btnSorteioActionPerformed

    private void txtSegundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSegundoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSegundoActionPerformed

    private void txtPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimeiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimeiroActionPerformed

    private void btnJogador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogador2ActionPerformed
        // TODO add your handling code here
         lblNumAnt.setText(Integer.toString(numant));    
         double numsorte = (Math.random()* (6 - 1) + 1);
        int resultado = (int)numsorte;
        int valor = Integer.parseInt(txtNum.getValue().toString()); 
        lblNumCorr.setText("Sorteado è o Número " + resultado);
          if (resultado == valor){
              lblFrase.setText("Acertou");
               playSound();
               placar2 = placar2 + 1;
               lblPlacar2.setText(Integer.toString(placar2));
               
          }else{
              lblFrase.setText("Errou");
              playErrou();
           }   
            numant=resultado;
       
        
    }//GEN-LAST:event_btnJogador2ActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // Reiniciar o jogo:
        lblPlacar1.setText(""); 
        lblPlacar2.setText("");
                   placar1 = 0;
                   placar2 = 0;
    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
         
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAcertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAcertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAcertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAcertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAcertar().setVisible(true);
                
          }
      });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnJogador2;
    private javax.swing.JButton btnSorteio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblFrase;
    private javax.swing.JLabel lblNumAnt;
    private javax.swing.JLabel lblNumCorr;
    private javax.swing.JLabel lblPlacar1;
    private javax.swing.JLabel lblPlacar2;
    private javax.swing.JSpinner txtNum;
    private javax.swing.JTextField txtPrimeiro;
    private javax.swing.JTextField txtSegundo;
    // End of variables declaration//GEN-END:variables

 
   
}
